
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - authentication-mongo

  webapi:
    container_name: webapi
    build:
      context: .
    ports:
      - "5235:80"
    networks:
      - authentication-mongo
    environment:
      ConnectionString: mongodb://root:example@authentication-mongo:27017
    depends_on:
      - mongodb
    volumes:
      - dataprotection:/root/.aspnet/DataProtection-Keys

volumes:
  dataprotection:

networks:
  authentication-mongo:
    driver: bridge